service: crypto-tracker-api

provider:
  name: aws
  runtime: nodejs6.10

functions:
  createUser:
    handler: src/app.handler
    events:
      - http:
          path: test
          method: get
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 5000